# Generated by Django 5.0.3 on 2024-03-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Residential', 'Residential'), ('Work', 'Work'), ('Permanent', 'Permanent')], max_length=32)),
                ('location', models.CharField(max_length=128)),
                ('building_no', models.CharField(blank=True, default='', max_length=32)),
                ('city', models.CharField(max_length=128)),
                ('region', models.CharField(max_length=64)),
                ('postal_code', models.CharField(blank=True, default='', max_length=32)),
                ('digital_code', models.CharField(blank=True, default='', max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
