# Generated by Django 5.0.9 on 2024-11-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pin_used_by_user_school_alter_pin_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
